name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest    # corrected from 'ubuntu:letest'
    steps:
      - name: Code checkout
        uses: actions/checkout@v5

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle
