name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest    # corrected from 'ubuntu:letest'
    steps:
      - name: Testing workflow
        run: echo "Workflow works"
